### ISSUE TITLE
Improvement in the Card UI section

### ISSUE THREAD

**Issue by om453** [M-ayank2005/Foodie#11]
Hey @M-ayank2005  

Description :
I reviewed the project and there needs a lot of improvement in this Section specially in text and hover effect over each card

![Screenshot 2024-10-14 200006](https://github.com/user-attachments/assets/0b6da069-7141-4056-b998-085a386ef99c)

Expected Changes 
- I want to add content and framer motion in text 
- I want to add attractive hover effect on the card  

Kindly assign me this issue and do add label hacktoberfest , hacktoberfest-accepted and ggsoc-ext 24

**Comment by M-ayank2005** [comment]
Kindly suggest the improvement you like to implement.
Also add screenshots of the improvements

**Comment by om453** [comment]
Sure,  @M-ayank2005 these are the changes which i have done 

https://github.com/user-attachments/assets/9df13424-f531-4796-9d78-c9fa59768ce1

**Comment by M-ayank2005** [comment]
Some changes were already made first you have to pull them.
I am assigning you this issue.

**Comment by om453** [comment]
> Some changes were already made first you have to pull them. I am assigning you this issue.

sure  @M-ayank2005  and pls add those label hacktoberfest , hacktoberfest-accepted and ggsoc-ext 24 in this issue as well

**Comment by om453** [comment]
@M-ayank2005  Raised a Pull Request
