### ISSUE TITLE
Improve Login/Signup Page UI

### ISSUE THREAD

**Issue by M-ayank2005** [M-ayank2005/Foodie#12]
### Description
The current login/signup page UI needs improvement to enhance the user experience and make it visually appealing.

### Suggested Changes
- Update the layout to be more modern and user-friendly.
- Use better spacing and alignment for form fields and buttons.
- Add Tailwind CSS styling for better aesthetics.
- Include animations or transitions for form elements.
- Ensure the page is responsive and works well on both mobile and desktop devices.

### Additional Context
- Consider using a consistent color scheme that matches the overall theme of the application.
- Optionally, add social login buttons for easier authentication.

**Comment by SaumyaSubham** [comment]
Hii @M-ayank2005 
I want to work on this issue and Can you locate the file or folder that I'll work on, it helps me to find the file and start fixing quickly. Kindly assign me this issue under hacktoberfest2024

**Comment by M-ayank2005** [comment]
@SaumyaSubham  you are assigned this issue .you have to work on login form and loginpage page.js .

**Comment by SaumyaSubham** [comment]
@M-ayank2005 Sorry, I didn't get it! Where is your login form or page.js? Are you mean this location src/Components/AuthForm.jsx because you have given here the styles
Or this location:
src/app/LoginPage/page.jsx

**Comment by M-ayank2005** [comment]
Yes you need to edit styles of both the pages to improve the ui

**Comment by M-ayank2005** [comment]
@SaumyaSubham  please look at the deployment issue ![Screenshot_20241016_114554.jpg](https://github.com/user-attachments/assets/008bbd2b-5abf-4e32-8f05-a9492095b14a)

**Comment by SaumyaSubham** [comment]
Sure! I'm looking upto it
