### ISSUE TITLE
Redirect to Home Page After Successful Login

### ISSUE THREAD

**Issue by M-ayank2005** [M-ayank2005/Foodie#13]
### Description
After a successful login, the user should be automatically redirected to the home page instead of staying on the login/signup page.

### Expected Behavior
- Once the login process completes successfully, the app should navigate to the home page.
- The redirection should happen seamlessly without requiring any manual user action.

### Suggested Solution
- Implement a redirect function that triggers after login success.
- Use Next.js router (or your preferred navigation method) to navigate to the home page.

### Additional Context
- Ensure that the user's authentication state is properly updated before the redirection.
- Optionally, display a success message or toast notification before the redirect.

**Comment by 2021eo3ar** [comment]
Hey @M-ayank2005 assign me this issue, I will come up with a better solution

**Comment by M-ayank2005** [comment]
@2021eo3ar  I have assigned you. Go ahead.

**Comment by 2021eo3ar** [comment]
yes, I will update you once done

**Comment by Naumantamboli** [comment]
can you please assign me this issue.I would like to work on this one
