### ISSUE TITLE
Fix Login and Signup with Email and Password

### ISSUE THREAD

**Issue by M-ayank2005** [M-ayank2005/Foodie#14]
### Description
The login and signup functionalities using email and password are currently not working as expected. This issue needs to be addressed to ensure users can authenticate successfully.

### Problem
- Users are unable to log in or sign up using their email and password.
- There might be issues with form validation, authentication logic, or Firebase configuration.

### Suggested Solution
- Review the authentication flow and fix any issues related to email/password login and signup.
- Ensure form validation is correctly implemented.
- Verify Firebase configuration for authentication is set up properly.
- Add error handling to display appropriate error messages for failed login/signup attempts.

### Additional Context
- Check for any relevant error messages in the console or network tab during authentication.
- Test both login and signup functionalities after the fix.

**Comment by ishan657** [comment]
HI @M-ayank2005 
I have understood the problem and want to contribute on this issue, kindly assign it to me 
thankyou

**Comment by M-ayank2005** [comment]
@ishan657  you are assigned. Go ahead with solution.

**Comment by anurag2787** [comment]
Hey @M-ayank2005 can you assign this issue to me. I have solved this issue

**Comment by M-ayank2005** [comment]
@anurag2787  I am assigning you.
