### ISSUE TITLE
Improve Navbar UI for Better Usability and Visual Appeal

### ISSUE THREAD

**Issue by M-ayank2005** [M-ayank2005/Foodie#15]
Description: The current Navbar UI can be improved to provide a more visually appealing and user-friendly experience. Some enhancements can be made in terms of layout, spacing, colors, and interactivity.

Enhancements to Consider:

1. Logo Alignment: Ensure that the logo is aligned properly with the navigation links on all screen sizes.

2. Mobile Responsiveness: Improve the Navbar layout for mobile devices to ensure smooth transitions and accessibility.

3. Spacing: Adjust the spacing between the logo, navigation links, and the logout button for better readability.

4. Hover Effects: Add subtle hover effects to the navigation links to enhance interactivity.

5. Active Link Styling: Add distinct styles for the active link to indicate the current page.

6. Color Scheme: Update the color scheme to better align with the overall website design for a cohesive look.

7. Dropdown Menu (if applicable): Improve the visibility and functionality of dropdown menus on smaller devices.

8. Logout Button: Style the logout button to make it more prominent and visually distinct from the navigation links.

Screenshots/Mockups:

Add any relevant screenshots or mockups showing the current state of the Navbar and the proposed improvements.

Expected Outcome:

The Navbar should be more intuitive and visually pleasing, with improved spacing, responsiveness, and a clear active link indicator.

Additional Notes:

Ensure cross-browser compatibility and test on various screen sizes.

**Comment by shiv-0101** [comment]
can you share current navbar's screenshots

**Comment by M-ayank2005** [comment]
You can view on your localhost or on deployed version.

**Comment by ishan657** [comment]
HI @M-ayank2005 
I would love to work on this issue, kindly assign it to me 
thankyou

**Comment by M-ayank2005** [comment]
@ishan657  you are assigned now.

**Comment by ishan657** [comment]
How much time do I get to work on the issue once I get assigned to make a pull request? just asking

**Comment by M-ayank2005** [comment]
You can do by today.

**Comment by ishan657** [comment]
Hello @M-ayank2005 
Can I submit my pr tomorrow as i was engaged with my college work today , Please give me one more day to complete this issue 
Thank you for understanding.

**Comment by ishan657** [comment]
hello @M-ayank2005 
I am not able to push my changes to my updatebranch and it says that i need to have permission to do so , 
Kindly help me in this scenario.

**Comment by M-ayank2005** [comment]
@ishan657  I don't think such issue should appear. Can you please attach the screenshot of the issues you are facing.

**Comment by ishan657** [comment]
gg

![Screenshot 2024-10-17 225349](https://github.com/user-attachments/assets/207949d7-d48c-430d-94b1-e957bd1e9c76)

**Comment by M-ayank2005** [comment]
@ishan657  you have cloned my repo directly.This is wrong way.
You have to first fork my repo.Then clone forked repo and work on that.

**Comment by ishan657** [comment]
Thanks for helping me out I will take care from next time .. and this was my first time contributing to open source so I wasn't that sure.. 😔 ..
