### ISSUE TITLE
The Tailwind css is not correctly working on deployed version but works fine on localhost

### ISSUE THREAD

**Issue by M-ayank2005** [M-ayank2005/Foodie#2]
Title: Tailwind CSS Not Working on Deployed Version

Description:

I am experiencing an issue where Tailwind CSS is functioning correctly on my localhost but does not seem to work on the deployed version of the application. Here are the details:
Steps to Reproduce:

    Run the application locally using npm start or yarn start.
    Confirm that Tailwind CSS styles are applied correctly in the browser.
    Deploy the application using [deployment method, e.g., Vercel, Netlify, etc.].
    Open the deployed application in the browser.
    Observe that Tailwind CSS styles are not applied.

Expected Behavior:

Tailwind CSS should work seamlessly in both local and deployed environments.
Actual Behavior:

In the deployed version, the Tailwind CSS styles do not apply, resulting in unstyled components.
Additional Information:

    Local Environment:
        Node.js version: [your version]
        Tailwind CSS version: [your version]
    Deployment Environment:
        Hosting Service: [e.g., Vercel, Netlify]
        Deployment URL: on project page

Possible Solutions Tried:

    Double-checked the Tailwind CSS configuration file (tailwind.config.js).
    Verified that the styles are being imported correctly in the main CSS file.
    Cleared the cache of the deployed site.

Screenshots:
Suggested Labels:

    bug
    help wanted
    hacktoberfest

**Comment by Zish303** [comment]
I think tailwind is installed as development dependency.
Please assign me this issue, I will solve this.

**Comment by M-ayank2005** [comment]
> I think tailwind is installed as development dependency.
> Please assign me this issue, I will solve this.

@Zish303  I have assigned the issue.Go ahead .

**Comment by Zish303** [comment]
@M-ayank2005 please share screenshot of the website in localhost and in vercel deployment.

**Comment by M-ayank2005** [comment]
@Zish303  have you not cloned the repo and run on localhost?
The deployment link already on repo.
