### ISSUE TITLE
[FEATURE]: Add Reviews section in food item detail page

### ISSUE THREAD

**Issue by saumy-sh** [M-ayank2005/Foodie#20]
It would be good to add **Review Section** in item detail page where users can share their review of the product. The comments will be shown along with username and date of posting. Also they will be arranged in latest first order. I would also create the backend for this.

**Comment by saumy-sh** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by M-ayank2005** [comment]
@saumy-sh  you are assigned. You can go ahead with implementation.

**Comment by saumy-sh** [comment]
Thanks, I am working on it!!

**Comment by saumy-sh** [comment]
Can you please add hacktoberfest-accepted label?

**Comment by M-ayank2005** [comment]
Okk I am adding it.

**Comment by saumy-sh** [comment]
Also it seems like you haven't pushed your backend here. For adding comment feature i will have to make changes in the backend to store them. Can you provide me access to backend as well, just the backend code?

**Comment by saumy-sh** [comment]
> Also it seems like you haven't pushed your backend here. For adding comment feature i will have to make changes in the backend to store them. Can you provide me access to backend as well, just the backend code?

@M-ayank2005  I won't be able to contribute if this isn't done.
