### ISSUE TITLE
Improving UI of Contact Us

### ISSUE THREAD

**Issue by anurag2787** [M-ayank2005/Foodie#28]
The Ui of contact us is not looking good even it not working on dark mode

**Comment by anurag2787** [comment]
@M-ayank2005  please assign this issue to me

**Comment by M-ayank2005** [comment]
@anurag2787  you are assigned

**Comment by M-ayank2005** [comment]
@anurag2787  are you working on this issue?

**Comment by anurag2787** [comment]
i am working on it
