### ISSUE TITLE
Feature: Dark mode

### ISSUE THREAD

**Issue by yube01** [M-ayank2005/Foodie#5]
Dark mode feature can be implemented

**Comment by M-ayank2005** [comment]
@yube01  I have assigned the issue you can go ahead with implementation 👍

**Comment by yube01** [comment]
@M-ayank2005  can you add hacktoberfest label as well

**Comment by M-ayank2005** [comment]
Okk I will add

**Comment by Daksh-134** [comment]
Hi @M-ayank2005  ,pls assign it to me if issue is still open

**Comment by M-ayank2005** [comment]
@yube01  are you working on this issue

**Comment by yube01** [comment]
@M-ayank2005 I'm working on it

**Comment by M-ayank2005** [comment]
Okk keep going

**Comment by anurag2787** [comment]
hey @M-ayank2005  please assign this issue to me

**Comment by M-ayank2005** [comment]
@anurag2787  you are assigned .Go ahead with implementation.

**Comment by M-ayank2005** [comment]
@anurag2787  .You have not fixed dark mode in profile page and contactus page.

**Comment by Daksh-134** [comment]
> @anurag2787 .You have not fixed dark mode in profile page and contactus page.

Hi @M-ayank2005 pls assign it to me
